# Generated by Django 5.0.4 on 2024-05-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_first_name_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='content_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='content_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
